version: '3.9'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: emoji-quest
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./docker/supervisor:/etc/supervisor/conf.d
      - ./docker/supervisor/supervisord.conf:/etc/supervisor/supervisord.conf
    container_name: app-eq
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    networks:
      - app-network
    command: /usr/bin/supervisord -c /etc/supervisor/supervisord.conf

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver-eq
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network


  #PgSQL Service
  db:
    image: postgres:15.1
    container_name: pgsql-eq
    volumes:
         - ./docker/data/pgsql:/var/lib/postgresql/data
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      SERVICE_TAGS: dev
      SERVICE_NAME: pgsql
    networks:
      - app-network
  centrifugo:
      image: centrifugo/centrifugo:v5
      container_name: centrifugo-eq
      environment:
          - CENTRIFUGO_TOKEN_HMAC_SECRET_KEY=${CENTRIFUGO_SECRET}
          - CENTRIFUGO_API_KEY=${CENTRIFUGO_APIKEY}
          - CENTRIFUGO_ADMIN_PASSWORD=${CENTRIFUGO_ADMIN_PASSWORD}
      volumes:
          - ./docker/centrifugo/config.json:/centrifugo/config.json
      command: centrifugo -c config.json
      restart: unless-stopped
      ports:
          - 8000:8000
      ulimits:
          nofile:
              soft: 65535
              hard: 65535
      networks:
          - app-network
  cache:
      image: redis:alpine
      container_name: redis-eq
      command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
      environment:
          REDIS_PASSWORD: "${REDIS_PASSWORD}"
      volumes:
          - ./docker/data/redis:/data
      restart: unless-stopped
      ports:
          - "6379:6379"
      networks:
          - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
